export const uiCopyKeys = [
  'boot_title',
  'shell_title',
  'shell_subtitle',
  'nav_dashboard',
  'nav_cpu',
  'nav_network',
  'nav_disk',
  'nav_probes',
  'nav_alerts',
  'nav_settings',
  'targets',
  'active_target',
  'overview',
  'theme',
  'language',
  'theme_dark',
  'theme_light',
  'language_zh',
  'language_en',
  'live',
  'idle',
  'unknown',
  'add_server',
  'status_loading',
  'status_error',
  'status_empty',
  'status_selection',
  'status_idle',
  'dashboard_title',
  'dashboard_desc',
  'stat_targets',
  'stat_selection',
  'stat_metrics',
  'stat_theme',
  'cpu_total',
  'memory_usage',
  'memory_cached',
  'memory_free',
  'network_ingress',
  'disk_write',
  'cpu_history',
  'memory_history',
  'network_history',
  'disk_history',
  'live_rankings',
  'storage_breakdown',
  'per_core_snapshot',
  'chart_empty',
  'loading_title',
  'loading_desc',
  'no_servers_title',
  'no_servers_desc',
  'selection_title',
  'selection_desc',
  'metrics_loading_title',
  'metrics_loading_desc',
  'metrics_error_title',
  'metrics_error_desc',
  'no_metrics_title',
  'no_metrics_desc',
  'stale_prefix',
  'cpu_page_title',
  'cpu_page_desc',
  'cpu_hot_core',
  'cpu_core_count',
  'cpu_matrix',
  'network_page_title',
  'network_page_desc',
  'network_interfaces',
  'network_busiest_rx',
  'network_busiest_tx',
  'network_matrix',
  'disk_page_title',
  'disk_page_desc',
  'disk_mount_count',
  'disk_hottest',
  'disk_busiest_write',
  'disk_usage',
  'disk_throughput',
  'settings_title',
  'settings_desc',
  'settings_registry',
  'settings_configured_targets',
  'settings_add_target',
  'settings_create_target',
  'settings_defaults',
  'settings_app_settings',
  'settings_display_title',
  'settings_display_desc',
  'settings_runtime_title',
  'settings_runtime_desc',
  'settings_delete_target',
  'settings_no_server_title',
  'settings_no_server_desc',
  'settings_name_placeholder',
  'settings_host_placeholder',
  'settings_name_label',
  'settings_host_label',
  'settings_port_label',
  'settings_polling_label',
  'settings_token_placeholder',
  'settings_save_target',
  'settings_save_settings',
  'settings_default_polling',
  'settings_retention_days',
  'settings_adapter',
  'settings_access_method',
  'adapter_go_agent',
  'adapter_node_exporter',
  'adapter_glances',
  'access_method_private',
  'access_method_tunnel',
  'access_method_gateway',
  'settings_theme_label',
  'settings_language_label',
  'settings_ssh_key_placeholder',
  'settings_ssh_passphrase_placeholder',
  'server_target_label',
  'server_active',
  'server_ready',
  'probe_title',
  'probe_desc',
  'probe_scope_title',
  'probe_scope_desc',
  'probe_signals_title',
  'probe_active_target_desc',
  'probe_signal_icmp',
  'probe_signal_tcp',
  'probe_signal_dns',
  'deferred_notice',
  'alert_title',
  'alert_desc',
  'alert_scope_title',
  'alert_scope_desc',
  'alert_future_title',
  'alert_active_target_desc',
  'alert_signal_threshold',
  'alert_signal_routing',
  'alert_signal_history',
  'server_count_total',
  'server_count_online',
  'server_count_offline',
  'active_server_label',
  'auth_type_label',
  'auth_type_token',
  'auth_type_ssh_key',
  'auth_type_password',
  'ssh_key_path_label',
  'ssh_passphrase_label',
  'password_label',
  'network_egress',
  'total_consumed',
  'disk_read_speed',
  'disk_write_speed',
  'total_capacity',
] as const;

export type UiCopyKey = (typeof uiCopyKeys)[number];
type UiDictionary = Record<UiCopyKey, string>;

export const zhCN: UiDictionary = {
  boot_title: '遥测控制台',
  shell_title: '运维控制台',
  shell_subtitle: '只保留控制台和设置两块工作区，用更高的信息密度查看整组服务器状态。',
  nav_dashboard: '控制台',
  nav_cpu: 'CPU',
  nav_network: '网络',
  nav_disk: '磁盘',
  nav_probes: '探测',
  nav_alerts: '告警',
  nav_settings: '设置',
  targets: '目标',
  active_target: '活动目标',
  overview: '总览',
  theme: '主题',
  language: '语言',
  theme_dark: '深色',
  theme_light: '浅色',
  language_zh: '中文',
  language_en: 'English',
  live: '在线',
  idle: '空闲',
  unknown: '等待中',
  server_count_total: '服务器总数',
  server_count_online: '在线',
  server_count_offline: '离线',
  active_server_label: '活动服务器',
  auth_type_label: '认证方式',
  auth_type_token: '令牌认证',
  auth_type_ssh_key: 'SSH 密钥',
  auth_type_password: '密码认证',
  ssh_key_path_label: '私钥路径',
  ssh_passphrase_label: '密钥密码',
  password_label: '密码',
  network_egress: '出站流量',
  total_consumed: '合计吞吐',
  disk_read_speed: '读取速度',
  disk_write_speed: '写入速度',
  total_capacity: '总容量',
  add_server: '前往设置添加服务器',
  status_loading: '加载中',
  status_error: '错误',
  status_empty: '空状态',
  status_selection: '待选择',
  status_idle: '空闲',
  dashboard_title: '所有服务器状态与当前目标详情',
  dashboard_desc: '左侧快速横向对比整组服务器，右侧聚焦当前目标的 CPU、内存、网络与磁盘面板。',
  stat_targets: '目标数',
  stat_selection: '当前状态',
  stat_metrics: '样本数',
  stat_theme: '当前主题',
  cpu_total: 'CPU 总使用率',
  memory_usage: '内存占用',
  memory_cached: '缓存',
  memory_free: '空闲',
  network_ingress: '网络接收',
  disk_write: '磁盘写入',
  cpu_history: 'CPU 趋势',
  memory_history: '内存趋势',
  network_history: '网络吞吐',
  disk_history: '磁盘吞吐',
  live_rankings: '实时排行',
  storage_breakdown: '存储与网络摘要',
  per_core_snapshot: '核心快照',
  chart_empty: '暂无历史样本',
  loading_title: '正在装载控制面状态',
  loading_desc: '正在读取本地持久化的服务器和设置，完成后会切换到真实运行态。',
  no_servers_title: '还没有监控目标',
  no_servers_desc: '先添加一个 Go Agent 或 Node Exporter 目标，再进入实时监控。',
  selection_title: '请选择一个活动服务器',
  selection_desc: '侧边栏中的目标卡片决定当前监控上下文。',
  metrics_loading_title: '正在等待首轮采集',
  metrics_loading_desc: '轮询已启动，首批数据写入后这里会切到真实图表。',
  metrics_error_title: '实时指标拉取失败',
  metrics_error_desc: '当前目标的最新指标无法读取，请检查 agent 连通性与本地数据库。',
  no_metrics_title: '还没有可显示的指标',
  no_metrics_desc: '目标已选中，但数据库里还没有这台机器的最新样本。',
  stale_prefix: '最新拉取失败，当前展示的是上一批成功样本：',
  cpu_page_title: 'CPU 负载需要趋势，不只是瞬时数值。',
  cpu_page_desc: '总利用率和每核心分布一起显示，方便判断瓶颈是持续升高还是局部爆发。',
  cpu_hot_core: '最热点核心',
  cpu_core_count: '核心数量',
  cpu_matrix: '核心矩阵',
  network_page_title: '网络页应该优先展示流量变化，而不是孤立卡片。',
  network_page_desc: '把最繁忙接口的接收和发送趋势放到前面，避免接口名和数值互相挤压。',
  network_interfaces: '接口数量',
  network_busiest_rx: '最高接收',
  network_busiest_tx: '最高发送',
  network_matrix: '接口矩阵',
  disk_page_title: '磁盘页需要同时表达容量压力和读写节奏。',
  disk_page_desc: '容量占用留在摘要列表，读写速率上图，避免长挂载名和百分比重叠。',
  disk_mount_count: '挂载点数量',
  disk_hottest: '最高占用',
  disk_busiest_write: '最高写入',
  disk_usage: '容量占用',
  disk_throughput: '读写吞吐',
  settings_title: '服务器注册与运行偏好',
  settings_desc: '这里负责维护服务器清单、接入认证方式，以及桌面端的轮询和显示偏好。',
  settings_registry: '目标注册表',
  settings_configured_targets: '服务器清单',
  settings_add_target: '新增目标',
  settings_create_target: '创建监控目标',
  settings_defaults: '默认设置',
  settings_app_settings: '应用偏好',
  settings_display_title: '显示与语言',
  settings_display_desc: '主题和语言在桌面窗口内即时保存，避免继续占用全局顶栏空间。',
  settings_runtime_title: '轮询与保留策略',
  settings_runtime_desc: '这里控制新目标的默认采集频率，以及本地历史指标的保留周期。',
  settings_delete_target: '删除该目标',
  settings_no_server_title: '还没有持久化的服务器',
  settings_no_server_desc: '提交右侧表单后，Tauri 持久化命令会把服务器保存到本地 SQLite，并立即回流到侧边栏和仪表盘。',
  settings_name_placeholder: '显示名称',
  settings_host_placeholder: '主机 / IP',
  settings_name_label: '名称',
  settings_host_label: '主机 / IP',
  settings_port_label: '端口',
  settings_polling_label: '轮询周期',
  settings_token_placeholder: '输入访问令牌（Go Agent 可选）',
  settings_save_target: '保存并接入目标',
  settings_save_settings: '保存应用设置',
  settings_default_polling: '默认轮询秒数',
  settings_retention_days: '数据保留天数',
  settings_adapter: '采集适配器',
  settings_access_method: '接入方式',
  adapter_go_agent: 'Go Agent',
  adapter_node_exporter: 'Node Exporter',
  adapter_glances: 'Glances',
  access_method_private: '内网直连',
  access_method_tunnel: '隧道转发',
  access_method_gateway: '网关中转',
  settings_theme_label: '主题',
  settings_language_label: '语言',
  settings_ssh_key_placeholder: '输入私钥文件路径',
  settings_ssh_passphrase_placeholder: '如果密钥已加密，请输入解锁密码',
  server_target_label: '目标',
  server_active: '活动中',
  server_ready: '就绪',
  probe_title: '探测能力暂时保持显式延后状态。',
  probe_desc: '当前 MVP 修复只覆盖目标注册、指标拉取与监控展示，Probe 页面明确展示范围，而不是伪造不可用流程。',
  probe_scope_title: '延后中的探测调度',
  probe_scope_desc: '真实的 Ping / TCP / DNS 调度还没有接入桌面调度器，因此这里不会伪造延迟数字。',
  probe_signals_title: '计划中的探测信号',
  probe_active_target_desc: '已注册 {count} 台目标，后续 probe 调度将沿用当前活动目标作为默认上下文。',
  probe_signal_icmp: 'ICMP 延迟',
  probe_signal_tcp: 'TCP 建连时间',
  probe_signal_dns: 'DNS 解析时间',
  deferred_notice: '当前在后续 OpenSpec 变更中实现。',
  alert_title: '告警模块保留真实边界，不伪造工作流。',
  alert_desc: '后端里已有告警模型和存储骨架，但规则编排和运维流仍未进入本次 MVP 修复范围。',
  alert_scope_title: '规则界面尚未接入',
  alert_scope_desc: '桌面端当前不提供规则编辑、事件流浏览或通知编排，这个页面只展示真实范围。',
  alert_future_title: '后续工作流',
  alert_active_target_desc: '已注册 {count} 台目标。真正的 alert workflow 将在后续 change 中补齐。',
  alert_signal_threshold: '阈值规则',
  alert_signal_routing: '通知路由',
  alert_signal_history: '告警事件历史',
};

export const enUS: UiDictionary = {
  boot_title: 'Telemetry Console',
  shell_title: 'Operations Console',
  shell_subtitle: 'Keep the desktop app focused on two work surfaces only: console and settings.',
  nav_dashboard: 'Console',
  nav_cpu: 'CPU',
  nav_network: 'Network',
  nav_disk: 'Disk',
  nav_probes: 'Probes',
  nav_alerts: 'Alerts',
  nav_settings: 'Settings',
  targets: 'Targets',
  active_target: 'Active Target',
  overview: 'Overview',
  theme: 'Theme',
  language: 'Language',
  theme_dark: 'Dark',
  theme_light: 'Light',
  language_zh: '中文',
  language_en: 'English',
  live: 'Live',
  idle: 'Idle',
  unknown: 'Waiting',
  server_count_total: 'Total Servers',
  server_count_online: 'Online',
  server_count_offline: 'Offline',
  active_server_label: 'Active Server',
  auth_type_label: 'Authentication Method',
  auth_type_token: 'Bearer Token',
  auth_type_ssh_key: 'SSH Key',
  auth_type_password: 'Password',
  ssh_key_path_label: 'Private Key Path',
  ssh_passphrase_label: 'Passphrase',
  password_label: 'Password',
  network_egress: 'Egress',
  total_consumed: 'Combined Flow',
  disk_read_speed: 'Read Speed',
  disk_write_speed: 'Write Speed',
  total_capacity: 'Total Capacity',
  add_server: 'Add a server in Settings',
  status_loading: 'Loading',
  status_error: 'Error',
  status_empty: 'Empty',
  status_selection: 'Selection',
  status_idle: 'Idle',
  dashboard_title: 'Fleet status on the left, active server detail on the right.',
  dashboard_desc: 'Compare every server at a glance, then drill into CPU, memory, network, and disk for the selected target.',
  stat_targets: 'Targets',
  stat_selection: 'Selection',
  stat_metrics: 'Samples',
  stat_theme: 'Theme',
  cpu_total: 'CPU Usage',
  memory_usage: 'Memory Use',
  memory_cached: 'Cached',
  memory_free: 'Free',
  network_ingress: 'Ingress',
  disk_write: 'Disk Write',
  cpu_history: 'CPU History',
  memory_history: 'Memory History',
  network_history: 'Network Throughput',
  disk_history: 'Disk Throughput',
  live_rankings: 'Live Rankings',
  storage_breakdown: 'Storage and network summary',
  per_core_snapshot: 'Per-core snapshot',
  chart_empty: 'No history yet',
  loading_title: 'Loading control-plane state',
  loading_desc: 'Reading persisted servers and settings before switching the shell into live mode.',
  no_servers_title: 'No monitoring targets yet',
  no_servers_desc: 'Add a go_agent or node_exporter target before opening the live monitoring surface.',
  selection_title: 'Select an active server',
  selection_desc: 'The target card in the sidebar determines the current monitoring context.',
  metrics_loading_title: 'Waiting for the first poll',
  metrics_loading_desc: 'Polling has started. This view will switch to real charts after the first samples land.',
  metrics_error_title: 'Failed to load live metrics',
  metrics_error_desc: 'The latest metrics for this target could not be loaded. Check agent connectivity and the local database.',
  no_metrics_title: 'No metrics available yet',
  no_metrics_desc: 'A target is selected, but the database has not stored recent samples for it yet.',
  stale_prefix: 'Latest polling failed. Showing the last successful sample batch: ',
  cpu_page_title: 'CPU load needs trend lines, not just instant numbers.',
  cpu_page_desc: 'Show total utilization and per-core distribution together so operators can see whether pressure is sustained or isolated.',
  cpu_hot_core: 'Hottest Core',
  cpu_core_count: 'Core Count',
  cpu_matrix: 'Core Matrix',
  network_page_title: 'The network page should lead with flow changes, not isolated cards.',
  network_page_desc: 'Bring the busiest interface to the front and keep names from colliding with throughput values.',
  network_interfaces: 'Interfaces',
  network_busiest_rx: 'Top RX',
  network_busiest_tx: 'Top TX',
  network_matrix: 'Interface Matrix',
  disk_page_title: 'Disk views should show both capacity pressure and I/O rhythm.',
  disk_page_desc: 'Keep capacity in ranked summaries and move read and write behavior into charts so long mount names stay readable.',
  disk_mount_count: 'Mounts',
  disk_hottest: 'Highest Use',
  disk_busiest_write: 'Top Write',
  disk_usage: 'Capacity Usage',
  disk_throughput: 'Read/Write Throughput',
  settings_title: 'Server registry and runtime preferences',
  settings_desc: 'Manage the server list, authentication method, polling cadence, and shell preferences from one place.',
  settings_registry: 'Target Registry',
  settings_configured_targets: 'Server registry',
  settings_add_target: 'Add Target',
  settings_create_target: 'Create monitoring target',
  settings_defaults: 'Defaults',
  settings_app_settings: 'Application settings',
  settings_display_title: 'Appearance & Language',
  settings_display_desc: 'Theme and language apply immediately inside the desktop window instead of living in the global header.',
  settings_runtime_title: 'Polling & Retention',
  settings_runtime_desc: 'Control the default collection cadence for new targets and how long local history is kept.',
  settings_delete_target: 'Delete target',
  settings_no_server_title: 'No persisted servers yet',
  settings_no_server_desc: 'Submitting the form saves a target to local SQLite through Tauri and immediately feeds it back into the sidebar and dashboard.',
  settings_name_placeholder: 'Display name',
  settings_host_placeholder: 'Host / IP',
  settings_name_label: 'Name',
  settings_host_label: 'Host / IP',
  settings_port_label: 'Port',
  settings_polling_label: 'Polling',
  settings_token_placeholder: 'Bearer token (optional for go_agent)',
  settings_save_target: 'Save and connect target',
  settings_save_settings: 'Save application settings',
  settings_default_polling: 'Default polling seconds',
  settings_retention_days: 'Retention days',
  settings_adapter: 'Adapter',
  settings_access_method: 'Access method',
  adapter_go_agent: 'Go Agent',
  adapter_node_exporter: 'Node Exporter',
  adapter_glances: 'Glances',
  access_method_private: 'Private',
  access_method_tunnel: 'Tunnel',
  access_method_gateway: 'Gateway',
  settings_theme_label: 'Theme',
  settings_language_label: 'Language',
  settings_ssh_key_placeholder: 'Enter private key path',
  settings_ssh_passphrase_placeholder: 'Enter the passphrase if the key is encrypted',
  server_target_label: 'Target',
  server_active: 'ACTIVE',
  server_ready: 'READY',
  probe_title: 'Probe capabilities stay explicitly deferred.',
  probe_desc: 'The repaired MVP covers target registration, metric ingestion, and monitoring views. This page shows the real boundary instead of a fake workflow.',
  probe_scope_title: 'Deferred probe scheduler',
  probe_scope_desc: 'Real Ping, TCP, and DNS scheduling is not wired into the desktop scheduler yet, so this page does not fake latency values.',
  probe_signals_title: 'Planned probe signals',
  probe_active_target_desc: '{count} targets are registered. Future probe scheduling will inherit the current active target as its default context.',
  probe_signal_icmp: 'ICMP latency',
  probe_signal_tcp: 'TCP connect time',
  probe_signal_dns: 'DNS resolve time',
  deferred_notice: 'Deferred to a later OpenSpec change.',
  alert_title: 'Alerting keeps the true scope visible instead of faking a workflow.',
  alert_desc: 'Alert models and storage primitives exist in the backend, but rule authoring and operator workflows are still outside this MVP repair.',
  alert_scope_title: 'Rule UI is deferred',
  alert_scope_desc: 'The desktop client does not currently expose rule editing, event browsing, or notification orchestration. This page shows the real scope only.',
  alert_future_title: 'Future workflow',
  alert_active_target_desc: '{count} targets are registered. The real alert workflow will land in a later change.',
  alert_signal_threshold: 'Threshold rules',
  alert_signal_routing: 'Notification routing',
  alert_signal_history: 'Alert event history',
};

export const dictionaries = {
  'zh-CN': zhCN,
  'en-US': enUS,
} as const;
